
// these come from libhdhomerun/hdhomerun_pkt.h

const HDHOMERUN_DISCOVER_UDP_PORT = 65001
const HDHOMERUN_CONTROL_TCP_PORT = 65001
const HDHOMERUN_MAX_PACKET_SIZE = 1460
const HDHOMERUN_MAX_PAYLOAD_SIZE = 1452
const HDHOMERUN_TYPE_DISCOVER_REQ = 0x0002
const HDHOMERUN_TYPE_DISCOVER_RPY = 0x0003
const HDHOMERUN_TYPE_GETSET_REQ = 0x0004
const HDHOMERUN_TYPE_GETSET_RPY = 0x0005
const HDHOMERUN_TYPE_UPGRADE_REQ = 0x0006
const HDHOMERUN_TYPE_UPGRADE_RPY = 0x0007
const HDHOMERUN_TAG_DEVICE_TYPE = 0x01
const HDHOMERUN_TAG_DEVICE_ID = 0x02
const HDHOMERUN_TAG_GETSET_NAME = 0x03
const HDHOMERUN_TAG_GETSET_VALUE = 0x04
const HDHOMERUN_TAG_GETSET_LOCKKEY = 0x15
const HDHOMERUN_TAG_ERROR_MESSAGE = 0x05
const HDHOMERUN_TAG_TUNER_COUNT = 0x10

const HDHOMERUN_TAG_LINEUP_URL = 0x27

const HDHOMERUN_TAG_DEVICE_AUTH_BIN = 0x29
const HDHOMERUN_TAG_BASE_URL = 0x2A
const HDHOMERUN_TAG_DEVICE_AUTH_STR = 0x2B
const HDHOMERUN_DEVICE_TYPE_WILDCARD = 0xFFFFFFFF
const HDHOMERUN_DEVICE_TYPE_TUNER = 0x00000001
const HDHOMERUN_DEVICE_TYPE_STORAGE = 0x00000005
const HDHOMERUN_DEVICE_ID_WILDCARD = 0xFFFFFFFF
const HDHOMERUN_MIN_PEEK_LENGTH = 4

module.exports = {
  HDHOMERUN_DISCOVER_UDP_PORT,
  HDHOMERUN_CONTROL_TCP_PORT,
  HDHOMERUN_MAX_PACKET_SIZE,
  HDHOMERUN_MAX_PAYLOAD_SIZE,
  HDHOMERUN_TYPE_DISCOVER_REQ,
  HDHOMERUN_TYPE_DISCOVER_RPY,
  HDHOMERUN_TYPE_GETSET_REQ,
  HDHOMERUN_TYPE_GETSET_RPY,
  HDHOMERUN_TYPE_UPGRADE_REQ,
  HDHOMERUN_TYPE_UPGRADE_RPY,
  HDHOMERUN_TAG_DEVICE_TYPE,
  HDHOMERUN_TAG_DEVICE_ID,
  HDHOMERUN_TAG_GETSET_NAME,
  HDHOMERUN_TAG_GETSET_VALUE,
  HDHOMERUN_TAG_GETSET_LOCKKEY,
  HDHOMERUN_TAG_ERROR_MESSAGE,
  HDHOMERUN_TAG_LINEUP_URL,
  HDHOMERUN_TAG_TUNER_COUNT,
  HDHOMERUN_TAG_DEVICE_AUTH_BIN,
  HDHOMERUN_TAG_BASE_URL,
  HDHOMERUN_TAG_DEVICE_AUTH_STR,
  HDHOMERUN_DEVICE_TYPE_WILDCARD,
  HDHOMERUN_DEVICE_TYPE_TUNER,
  HDHOMERUN_DEVICE_TYPE_STORAGE,
  HDHOMERUN_DEVICE_ID_WILDCARD,
  HDHOMERUN_MIN_PEEK_LENGTH,
}
